Rewrite the logic of calculating liquid tokens by using implementation from core-contracts
near/account-lookup pull request #10
Opened 2021-08-02 13:43 UTC by telezhnaya

We've rewritten the solution from Rust to JS here https://github.com/near/near-explorer/blob/master/backend/src/aggregations.js

Put it here

I also had a war with the BN library, I needed to update the version to use the same as in near-explorer, that's why we have some diff in `yarn.lock`

2021-08-02 15:53 UTC, frol requested changes
While the code looks fine, it somehow breaks on some contracts:

`ed25519:6paKsDgqeeUQBfBU2V2wyUNGe2T4SZgVyCuB82jqd9nk` (you can lookup implicit accounts by the public key) from https://github.com/near/account-lookup/pull/7 is broken.

Please, check all the other PRs for the examples that caused issues previously and confirm that they run fine.

2021-08-02 15:53 UTC, frol commented on README.md
> +/usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run start
O_o

```suggestion
yarn
yarn start
```

2021-08-02 15:53 UTC, frol commented on script.js
> +        prefix_base64: "",
Revert it back

```
$ echo 'U1RBVEU=' | base64 -d
STATE
```

2021-08-02 15:55 UTC, telezhnaya commented on README.md
> +/usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run start
Sorry, I copy-pasted it from IDE 😄

2021-08-03 12:16 UTC, telezhnaya commented
Looks like I fixed #11, checked with `mike.near` (it looks a little different because includes owners balance, sounds logical) and `timp.near` (it has staking info).
Also checked all other examples: hopefully we cover all the examples now.
Please have a look again

2021-08-03 13:38 UTC, frol approved these changes
It seems to be working fine with my limited testing and reading the code. I hope it is the last time we need to fix it...

2021-08-03 13:38 UTC, merged