ADD fix for lockupTimestamp calc for broken timestamp contracts
near/account-lookup pull request #12
Opened 2021-10-22 16:03 UTC by esaminu

Fix issue where we return early in contracts with broken timestamps due to incorrect `lockupTimestamp` calculation in that case.

example: https://near.github.io/account-lookup/#cgran42.near

2021-10-22 20:54 UTC, frol requested changes
This fix is unfortunately not right.

cgran42.near account [was created](https://explorer.near.org/transactions/71yFYEKpBFCTwhkykGoYhyW5Sqvxi4HvcxdMfnkmxHmF) with the `lockup_duration` set to 3.5 years from Phase II launch. Thus, the contract still has all its tokens locked and it is reported correctly.

Having `lockup_duration` 3.5 years and `release_duration` set to `null` means that it will immediately unlocked 3.5 years from Oct 13, 2020 (Phase II launch).

There is still a bug in account lookup code which somehow misreports the release start date.

2021-10-22 22:12 UTC, esaminu commented
@frol My understanding is that `lockup_duration` is discarded for contracts that have one of [these code hashes](https://github.com/near/account-lookup/blob/master/script.js#L108). This appears to be the logic [here](https://github.com/near/account-lookup/blob/master/script.js#L180). We also have similar logic on the wallet [here](https://github.com/near/near-wallet/blob/master/packages/frontend/src/utils/account-with-lockup.js#L173). Calling ` get_liquid_owners_balance` on the contract shows a balance of `22535639954300000000`. This account has a `code_hash` of `3kVY9qcVRoW3B5498SMX6R3rtSLiCdmBzKs7zcnzDJ7Q`. [wallet display](https://wallet.near.org/profile/cgran42.near)

2021-11-06 15:32 UTC, frol commented
@esaminu Wallet implementation is broken. The source of truth is the contract, here we talk about [v2](https://github.com/near/core-contracts/blob/lockup-v2.0.0/lockup/src/getters.rs#L65-L113) version ([diff](https://github.com/near/core-contracts/commit/39e029619041b564ec08d33a8d65325b653b121b#diff-2846eb861dc09e92d16b219710c567d81afa363e6d2f5ebc4376385c1d43f168)).

> My understanding is that lockup_duration is discarded 

It is the other way around, `lockup_timestamp` is discarded in v2, which was patched in v3 (see the diff above).

2021-11-06 15:45 UTC, frol commented
@esaminu I am ooo next week, and I have been totally underwater with other tasks, so please collaborate with @telezhnaya on the matters here.

2021-11-08 16:26 UTC, esaminu commented
@frol @telezhnaya I think the key condition we missed is [this](https://github.com/near/core-contracts/blob/2691bd68a284cf519c1dd1927eb03be6fdd7a44b/lockup/src/getters.rs#L78) meaning the contract only considers `end_timestamp` if `start_timestamp` is greater than current time. If `start_timestamp` has not passed the contract just returns the [whole amount](https://github.com/near/core-contracts/blob/2691bd68a284cf519c1dd1927eb03be6fdd7a44b/lockup/src/getters.rs#L112) as locked. This is the case both on the "[broken timestamp contracts](https://github.com/near/core-contracts/blob/2691bd68a284cf519c1dd1927eb03be6fdd7a44b/lockup/src/getters.rs#L78)" and on the [latest](https://github.com/near/core-contracts/blob/master/lockup/src/getters.rs#L78). In the case of `cgran42.near`, the `end_timestamp` is actually less than the `start_timestamp` because of the [diff](https://github.com/near/core-contracts/blob/2691bd68a284cf519c1dd1927eb03be6fdd7a44b/lockup/src/getters.rs#L81) mentioned. I updated the PR on wallet: https://github.com/near/near-wallet/pull/2208 

This particular issue seems to be working correctly on account-lookup contrary to the complaint on telegram so I'm closing this 👍

2021-11-08 16:26 UTC, closed without merging